hidden_size: [8, 16, 32, 64, 128] 
loss_integral_num_sample_per_step: [5, 10, 20, 50]
time_emb_size: [8, 16, 32, 64, 128]
use_ln: [False, True]
num_layers: [1, 2, 3, 4]
num_heads: [1, 2, 4, 8]
dropout: (0.0, 0.3)
thinning:
  num_seq: 10 
  num_sample: 1
  num_exp: 500 # number of i.i.d. Exp(intensity_bound) draws at one time in thinning algorithm
  look_ahead_time: 10
  patience_counter: 5 # the maximum iteration used in adaptive thinning
  over_sample_rate: 5
  num_samples_boundary: 5
  dtime_max: 5
  num_step_gen: 1