hidden_size: [8, 16, 32, 64] 
time_emb_size: [8, 16, 32, 64] # Not used in S2P2
num_layers: [1, 2, 3]
loss_integral_num_sample_per_step: 5
model_specs:
  act_func: [full_glu, gelu, half_glu]
  dropout_rate: [0.0, 0.01, 0.05, 0.1, 0.2]
  pre_norm: [True, False]
  post_norm: [True, False]
  relative_time: [True, False]
  complex_values: [True, False]
  # simple_mark: False #[True, False]
  P: [2, 4, 8, 16, 32, 64]
