hidden_size: [8, 16, 32, 64] 
loss_integral_num_sample_per_step: 5
num_layers: [1, 2, 3]
model_specs:
  act_func: [full_glu, gelu, half_glu]
  dropout_rate: [0.0, 0.01, 0.05, 0.1, 0.2]
  pre_norm: [True, False]
  post_norm: [True, False]
  relative_time: [True, False]
  complex_values: [True, False]
  # simple_mark: False #[True, False]
  P: [2, 4, 8, 16, 32, 64]
thinning:
  num_seq: 4 
  num_sample: 1
  num_exp: 4 # number of i.i.d. Exp(intensity_bound) draws at one time in thinning algorithm
  look_ahead_time: 4
  patience_counter: 5 # the maximum iteration used in adaptive thinning
  over_sample_rate: 4
  num_samples_boundary: 5
  dtime_max: 4
  num_step_gen: 1